spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&useUnicode=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

pic:
  save:
    ip: 192.168.1.4
    path: /Users/zhangqiang/Desktop/chat-demo

sys:
  test: false
