# 指定环境
# 开发环境 - dev
# 生产环境 - prod
spring:
  application:
    name: cloud-chat-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1500MB # 单个文件大小
      max-request-size: 5000MB # 设置总上传的数据大小
      enabled: true #开启

server:
  port: 9004
  netty:
    port: 8000

mybatis:
  mapper-locations: classpath:mapper/*.xml

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

